### ISSUE TITLE
앞으로 고려해야할 사항(Next step we have to considered)

### ISSUE THREAD

**Issue by ukiKwon** [snrndi121/KBK_election#3]
#프로젝트(project) : kbk_election
#작성자(writer) : uki408
#작성날짜(date) : 2017-08-15

# The Issue List : Is completed?
- 코인 분배 (Coin distribution) : (done)
- 개표 (Counting) : (not yet)
- 마이닝 (Creating coins = mining) : (done)
- 트랜잭션 구성 (Transaction configuration) (done)

# 
$1. 코인 분배( Coin distribution ) (Trying)
: 어떻게 코인을 유권자에게 뿌릴것인가? (How to distribute coins to the other?)

$2. 개표( Counting ) 
: 블록체인에 들어간 정보들을 어떻게 가져와 어떤 형태로 뿌릴 것인가?(How do I get the Tx info from blockchain? And What the form displayed?)

$3. 마이닝( Mining )
: 코인을 어떻게 생성할 것인가?(How to create new coins)

$4. 새로운 트랜잭션 구성 ( A new transaction form is needed) (Solved)
: 투표를 위한 트랜잭션의 자료형은 어떻게 변경시켜야할 것인가?(What is the new transactions forms?)

$5. 트랜잭션 요금(Transaction Fee)
: 한쪽에서 요금을 0으로 만들었지만 전송이 안되는 상황( Now we face the error 'Tx fee = 0' )

**Comment by snrndi121** [comment]
$5. 트랜잭션 요금(Transaction Fee)
: 한쪽에서 요금을 0으로 만들었지만 전송이 안되는 상황( Now we face the error 'Tx fee = 0' )

**Comment by ukiKwon** [comment]
$1. 방안 찾음.
$2. -
$3. -
$4. 방안 찾음.
$5. -
